function d_matrix = plain_d_matrix( E1, E2, mu12, mu21, g12, alpha )  
    D_0_inv = [ 1/E1,     -mu21/E2,      0;...
                 -mu12/E1, 1/E2,     0;...
                 0,        0,        1/g12 ];
    D_0 = inv( D_0_inv );
    T_matrix = [ cos(alpha), -sin(alpha), 0;...
                 sin(alpha), cos(alpha),  0;...
                 0,          0,           1];
    d_matrix = transpose( T_matrix ) * D_0 * T_matrix;

end