function plot_diff_angles
    % Size of construction
    size_x = 4;
    size_y = 2;

    % Size of empty area (right-low)
    zero_dens_x = size_x / 8;
    zero_dens_y = size_y / 2.2;

    z_size = 0.05;

    force = -147099.75 / z_size;

    % Element size
    size_el = 0.05;

    % Mechanical properties for glass fiber ВМ-1
    E_fiber = 102.9e9;
    E_mx = 69.1e9;
    mu_fiber = 0.3;
    mu_mx = 0.3;
    vfc = 0.5;
    scale = 10;

    % Solver settings
    volfrac = 0.5; % max share of material in new construction
    penalty_degree = 3.0; % penalty function (rho)^p
    r_min = 1.5; % radius of filter
    file_id = fopen("u_matlab.txt", "A");

    generic_filename = "isotropic_sol";
    u_alpha_iso = top_comp(size_x, size_y, ...
        round(size_x / size_el), round(size_y / size_el), ...
        volfrac,penalty_degree,r_min, ...
        3*pi/4, 0, (E_fiber + E_mx)/2, (E_fiber + E_mx)/2, mu_fiber, mu_mx, scale, 400, ...
        zero_dens_x, zero_dens_y, force, generic_filename)
    fprintf(file_id, "u isotropic = %g\n", u_alpha_iso);
% 
%     generic_filename = sprintf("angle_%3d vfc_fib_%0.2f x_%.0f y_%.0f vfc_%0.2f", ...
%                                int8(0), vfc, size_x, size_y, volfrac);
%     u_alpha_0 = top_comp(size_x, size_y, ...
%             round(size_x / size_el), round(size_y / size_el), ...
%             volfrac,penalty_degree,r_min, ...
%             0, vfc, E_fiber, E_mx, mu_fiber, mu_mx, scale, 400, ...
%             zero_dens_x, zero_dens_y, force, generic_filename)
%     fprintf(file_id, "u 0 = %g\n", u_alpha_0);
% 
%     generic_filename = sprintf("angle_22_5 vfc_fib_%0.2f x_%.0f y_%.0f vfc_%0.2f", ...
%                                vfc, size_x, size_y, volfrac);
%     u_alpha_225 = top_comp(size_x, size_y, ...
%             round(size_x / size_el), round(size_y / size_el), ...
%             volfrac,penalty_degree,r_min, ...
%             pi/8, vfc, E_fiber, E_mx, mu_fiber, mu_mx, scale, 400, ...
%             zero_dens_x, zero_dens_y, force, generic_filename)
%     fprintf(file_id, "u 22.5 = %g\n", u_alpha_225);
% 
%     generic_filename = sprintf("angle_%3d vfc_fib_%0.2f x_%.0f y_%.0f vfc_%0.2f", ...
%                                int8(45), vfc, size_x, size_y, volfrac);
%     u_alpha_45 = top_comp(size_x, size_y, ...
%             round(size_x / size_el), round(size_y / size_el), ...
%             volfrac,penalty_degree,r_min, ...
%             pi/4, vfc, E_fiber, E_mx, mu_fiber, mu_mx, scale, 400, ...
%             zero_dens_x, zero_dens_y, force, generic_filename)
%     fprintf(file_id, "u 45 = %g\n", u_alpha_45);
% 
%     generic_filename = sprintf("angle_%3d vfc_fib_%0.2f x_%.0f y_%.0f vfc_%0.2f", ...
%                                int8(90), vfc, size_x, size_y, volfrac);
%     u_alpha_90 = top_comp(size_x, size_y, ...
%         round(size_x / size_el), round(size_y / size_el), ...
%         volfrac,penalty_degree,r_min, ...
%         pi/2, vfc, E_fiber, E_mx, mu_fiber, mu_mx, scale, 400, ...
%         zero_dens_x, zero_dens_y, force, generic_filename)
%     fprintf(file_id, "u 90 = %g\n", u_alpha_90);

    fclose('all');
end